GRANT SELECT ON TABLE IDENTIFIER('"PRACTICE_DB"."RAW_LAYER"."CUSTOMER"') TO ROLE IDENTIFIER('"CUSTOMEDBROLE"');
GRANT USAGE ON DATABASE IDENTIFIER('"PRACTICE_DB"') TO ROLE IDENTIFIER('"CUSTOMEDBROLE"');
GRANT USAGE ON SCHEMA  PRACTICE_DB.RAW_LAYER TO ROLE CUSTOMEDBROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA PRACTICE_DB.RAW_LAYER TO ROLE CUSTOMEDBROLE;

GRANT USAGE ON ALL OBJECTS IN SCHEMA PRACTICE_DB.RAW_LAYER TO ROLE CUSTOMEDBROLE;

SHOW GRANTS ON DATABASE PRACTICE_DB;


GRANT SELECT ON FUTURE TABLES IN SCHEMA PRACTICE_DB.RAW_LAYER TO ROLE CUSTOMEDBROLE;